### ISSUE TITLE
Would you be open to adding some build tools?

### ISSUE THREAD

**Issue by RedRiderX** [enthusiast94/reddit-reader-backbone#1]
Hey it's me from Reddit.

I was wanting to contribute, but first can I ask if I can add some simple build tools?

Here was what I was thinking of:
* Moving your build command into a package.json file, so it can be run by just typing `npm build`
* Instead of asking people to find their own localhost option, adding [BrowserSync](http://www.browsersync.io/), and hooking that into a `npm test` command or something
* I see you have a lot of seperate css files. Is a css preproccessor like Sass an option? This would let you easily combine them, among other things.

This is, of course, your project. You can take or leave any of these suggestions, but I'll probably have a  pr ready soon if you're interested.

**Comment by enthusiast94** [comment]
Hello Red, thanks for your interest. I'm all up for other developers
contributing to my project and making it better. All your suggestions are
quite good and you should go ahead with them.

**Comment by RedRiderX** [comment]
We can talk about my changes on the [pr](https://github.com/enthusiast94/reddit-reader-backbone/pull/2)
