### ISSUE TITLE
Add a sticky header

### ISSUE THREAD

**Issue by RedRiderX** [enthusiast94/reddit-reader-backbone#4]
A bit more of a suggestion, but having the header stick to the top or show on an upward scroll would be nice.

Would this be something that would be useful to add?

**Comment by enthusiast94** [comment]
A sticky header showing what exactly? Are you referring to the selected post on comments page?

**Comment by RedRiderX** [comment]
What I'm thinking of is the page filters (and maybe the menu button), showing when you scroll up. Something like an Android app.

![](http://i.imgur.com/ZAuy7Iq.png)

**Comment by enthusiast94** [comment]
Ah I see...seems like a great idea. Will add it to my TODO list.

**Comment by RedRiderX** [comment]
This was really well addressed in [the latest build](https://github.com/enthusiast94/reddit-reader-backbone/releases/tag/v1.0), nice job.

**Comment by enthusiast94** [comment]
Glad you liked it!
